### ISSUE TITLE
Composer found a Security Vulnerability

### ISSUE THREAD

**Issue by luchtech** [CyberSource/cybersource-rest-client-php#127]
Good day!

While installing your package, Composer told me that there's a security vulnerability. When I ran the `composer audit`, it showed me this:

<img width="841" alt="image" src="https://user-images.githubusercontent.com/26067874/233697258-03b1da85-9a90-4089-8e44-db01ea29b9d4.png">

Hopefully, someone can upgrade the version of `firebase/php-jwt` to `^6.0`.

Have a nice day ahead!

**Comment by monu-kumar-visa** [comment]
Hi @luchtech ,
This has been done from v0.0.41.
