### ISSUE TITLE
Flex Model KeyParameters is missing targetOrigin and other parameters

### ISSUE THREAD

**Issue by brianmc** [CyberSource/cybersource-rest-client-php#23]
In the PHP samples and also in my code which uses this PHP Client, the model class for KeyParameters (https://github.com/CyberSource/cybersource-rest-client-php/blob/master/lib/Model/KeyParameters.php) is not serializing all the parameters into the JSON payload.  Specifically targetOrigin is missing so when you add that to the sample code at https://github.com/CyberSource/cybersource-rest-samples-php/blob/master/Samples/Flex/CoreServices/GenerateKey.php as below, the parameter never makes it to the payload, as you can see from the log.

$flexRequestArr = [
	"encryptionType" => "RsaOaep256",
	**"targetOrigin" => "http://localhost:8000",**
	];
	$flexRequest = new CyberSource\Model\KeyParameters($flexRequestArr);

**Comment by gnongsie** [comment]
Hi Brian,
I have changed this to the correct model file for the request. 

Kindly review the change on the master branch.

**Comment by gnongsie** [comment]
Closing this issue based on the fix given in the samples repository.

**Comment by fl0cke** [comment]
This issue doesn't seem to be fixed. The model class is still missing the `targetOrigin` parameter.
