### ISSUE TITLE
Exception invalid length for $paymentSolution

### ISSUE THREAD

**Issue by gharbi-mohamed** [CyberSource/cybersource-rest-client-php#43]
Hi,

While testing **TransactionDetailsApi** api to track Paypal alternative payment through cybersource I'm facing a validation exception : 
Exception when calling TransactionDetailsApi->getTransaction: invalid length for $paymentSolution when calling TssV2TransactionsGet200ResponseProcessingInformation., must be smaller than or equal to 12.

I checked quickly an this is due to  **'paymentSolution' = 'Alternative Payment Paypal' (length=26)** :

> object(CyberSource\Model\TssV2TransactionsGet200ResponseProcessingInformation)[81]
>           protected 'container' => 
>             array (size=5)
>               'paymentSolution' => string 'Alternative Payment Paypal' (length=26)
>               'commerceIndicator' => null
>               'businessApplicationId' => null
>               'authorizationOptions' => 
>                 object(CyberSource\Model\TssV2TransactionsGet200ResponseProcessingInformationAuthorizationOptions)[82]
>                   protected 'container' => 
>                     array (size=1)
>                       'authType' => null
>               'bankTransferOptions' => 
>                 object(CyberSource\Model\TssV2TransactionsGet200ResponseProcessingInformationBankTransferOptions)[83]
>                   protected 'container' => 
>                     array (size=1)
>                       'secCode' => null

I guess the 12 size constraint should be modified as for alternative payments we have at least 26 chars ..., this is a critical bug which blocks transactions details check for altPay transactions.

In order to fix it in m project I made the following change in vendor/cybersource/rest-client-php/lib/Model/TssV2TransactionsGet200ResponseProcessingInformation.php:215 :

> public function setPaymentSolution($paymentSolution)
>     {
>         if (!is_null($paymentSolution) && (strlen($paymentSolution) > 28)) { // value was 12
>             throw new \InvalidArgumentException('invalid length for $paymentSolution when calling TssV2TransactionsGet200ResponseProcessingInformation., must be smaller than or equal to 28.');
>         }
>         $this->container['paymentSolution'] = $paymentSolution;
>         return $this;
>     }

Could you check ?

Thanks in advance.
Mohamed GHARBI

**Comment by gangadharsahoo** [comment]
Hi,
Thanks for bringing this to our notice. We have informed the issue to relevant team. Will update you as 
soon as we get the solution.

**Comment by kesz1tech** [comment]
Same error with American Express, any update?
/vendor/cybersource/rest-client-php/lib/ObjectSerializer.php(306): CyberSource\Model\TssV2TransactionsGet200ResponseProcessingInformation->setPaymentSolution('American Expres...')

**Comment by milosnovi** [comment]
@gangadharsahoo Hey guys, any update on this one? We encountered the same problem with America express

**Comment by monu-kumar-visa** [comment]
Hi,
The length check on the `paymentSolution` attribute has been removed from the SDK in version 0.0.19 and subsequent versions.
