### ISSUE TITLE
invalid length for $responseCategoryCode when calling PtsV2PaymentsPost201ResponseProcessorInformation., must be smaller than or equal to 32.

### ISSUE THREAD

**Issue by sauriio** [CyberSource/cybersource-rest-client-php#52]
Hi, as you can see on this issue's title, i have an error when the lib tries to convert the category code of the processorInformation.

**Comment by sauriio** [comment]
version 0.0.15

**Comment by chsriniv9** [comment]
@sauriio, Thank you for reporting the observation. We are looking into this and will get back with an update.

Thank you for your partnership

**Comment by gnongsie** [comment]
Hi,

This has been resolved with version 0.0.16. Closing this issue based on that.
