### ISSUE TITLE
Change the firebase/php-jwt version requirement to ^5.0

### ISSUE THREAD

**Issue by rszrama** [CyberSource/cybersource-rest-client-php#55]
This module forces an explicit dependency on php-jwt 5.0.0 even though subsequent versions of php-jwt above 5.0.0 but less than 6.0.0 should not introduce any breaking changes (assuming it conforms to semantic versioning, which I'd expect). The problem this creates is I have other dependencies in my project that require php-jwt ^5.0, meaning Composer has already installed 5.2.0 in my codebase and believes reverting to 5.0.0 to satisfy this library's requirement is a conflict.

If there's no explicit reason to require 5.0.0 for this library, can we update the requirement to ^5.0 to erase this conflict for myself and others. That should literally just have the affect of ensuring projects using this package have access to any bugfixes in php-jwt represented in those new minor versions.

**Comment by gnongsie** [comment]
Hi @rszrama,

I have tested this out and we can update this requirement. I have made this change in [this branch](https://github.com/CyberSource/cybersource-rest-client-php/tree/versions).

Kindly be patient and I will try to get this released as soon as possible.

**Comment by rszrama** [comment]
Cool, thanks! We'll keep our eyes on it. 🙂

**Comment by gnongsie** [comment]
Hi @rszrama,

I have released the new version (**v0.0.17**) with this dependency (`firebase/php-jwt`) upgraded to allow versions `>=5.0.0`.

Kindly verify it and I can close this issue.

**Comment by rszrama** [comment]
@gnongsie Cool, thanks so much!
