### ISSUE TITLE
Fails with Composer v2

### ISSUE THREAD

**Issue by mominsid** [CyberSource/cybersource-rest-client-php#59]
This package assumes `vendor/composer/installed.json` is in a Composer v1 format.

Here is a sample snippet of the Composer 2 version of this file:

```json
{
    "packages": [
        {
            "name": "altek/accountant",
            "version": "v2.0.3",
            "version_normalized": "2.0.3.0",
            // ...
        }
  ]
}
```

However, the function `CyberSource\ApiClient::getClientId` assumes that `packages` is at the top level,  which is no longer the case in the format listed above.

It fails at this line approx 155 where it tries to retrieve the property `name`:

```php

            if (strcmp($package['name'], "cybersource/rest-client-php") == 0)

```

**Comment by jezmck** [comment]
Duplicate of #58

**Comment by mominsid** [comment]
This doesn't look like a duplicate of #58 , but rather of #111. Closing.
