### ISSUE TITLE
- The requested package cybersource/global-payment-management could not be found in any version, there may be a typo in the package name.

### ISSUE THREAD

**Issue by faralimite** [CyberSource/cybersource-rest-client-php#7]
Hello,

We are one of your clients and we pay money every year. 
We launched a new website, developed in Magento 2, and the extension provided is not working:

```
Check Component Dependency
We found conflicting component dependencies. Hide detail

Command "update" failed: Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

Problem 1
- The requested package cybersource/global-payment-management could not be found in any version, there may be a typo in the package name.

Potential causes:
- A typo in the package name
- The package is not available in a stable-enough version according to your minimum-stability setting
see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

For additional assistance, see component dependency help .
```

I tried to contact cybersource magento support via email but NO ANSWER.

What can I do to use the extension? Why is so hard to contact someone from tech team to help us?

Regards,
Radu

**Comment by faralimite** [comment]
@chsriniv9 
the plugin that I'm trying to install is this one:https://marketplace.magento.com/cybersource-global-payment-management.html and is present in Extension manager: http://prntscr.com/lnaucw

and this one, is the official plugin according with marketplace and magento2.

When I click install => http://prntscr.com/lnaut3

I tried to contact M2_support@cybersource.com but not answer...

**Comment by faralimite** [comment]
@chsriniv9 
I managed now to install it.
Thank you!!!

**Comment by adnanhaiderVSI** [comment]
> @chsriniv9
> I managed now to install it.
> Thank you!!!

How? You should have listed steps so others like me who are having the same issue can get through with the installation process. Thank you

**Comment by CajuCLC** [comment]
@faralimite can you please post how you were able to install?

**Comment by CajuCLC** [comment]
@adnanhaiderVSI I figured it out as well.
You need to add the auth.json and then the repo information to composer.json: https://marketplace.magento.com/media/catalog/product/cybersource-global-payment-management-3-1-4-ee/installation_guides.pdf
